FROM python:3.10

# Install pip dependencies
RUN pip install 'matplotlib>=3.5' \
                'psutil>=5.8' \
                'tqdm>=4.59' \
                'pandas>=1.5' \
                'scipy>=1.9' \
                'numpy>=1.23,<2.0' \
                'ipykernel~=6.0' \
                'azureml-core' \
                'azureml-defaults' \
                'azureml-mlflow' \
                'azureml-telemetry' \
                'scikit-learn==1.5.2'

