FROM python:3.9

# Install pip dependencies
RUN pip install 'matplotlib>=3.5,<4' \
                'psutil' \
                'tqdm' \
                'pandas>=1.3,<2' \
                'scipy>=1.7,<2' \
                'numpy>=1.21,<2' \
                'ipykernel~=6.0' \
                'azureml-core' \
                'azureml-defaults' \
                'azureml-mlflow' \
                'azureml-telemetry' \
                'scikit-learn==1.3.2'

