name: imagecnn_train_conda_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.3.1
  - pip:
      - mldesigner==0.1.0b17
      - watchdog>=2.0.0
      - torch==2.5.1
      - torchvision==0.20.1
      - tensorboard>=2.10.0
      - pillow>=9.0.0
      - numpy>=1.23.0,<2.0
      - azureml-mlflow>=1.41.0
      - azure-common>=1.1.28
      - protobuf>=3.20.0
      - pandas>=1.5.0
      - packaging>=22.0