name: "model_name"
platform: "onnxruntime_onnx"
default_model_filename: "model_onnx_filename_si"
max_batch_size : 16 #MAX_BATCH
input [
   {
     name: "unique_ids_raw_output___9:0"
     data_type: TYPE_INT64
     dims: [ 1 ]
     reshape: { shape: [ ] }
   }
]
input [
   {
     name: "segment_ids:0"
     data_type: TYPE_INT64
     dims: [ 256 ]
   }
]
input [
   {
     name: "input_mask:0"
     data_type: TYPE_INT64
     dims: [ 256 ]
   }
]
input [
   {
     name: "input_ids:0"
     data_type: TYPE_INT64
     dims: [ 256 ]
   }
]		     
output [
   {
     name: "unstack:1"
     data_type: TYPE_FP32
     dims: [ 256 ]
   }
]
output [
   {
     name: "unstack:0"
     data_type: TYPE_FP32
     dims: [ 256 ]
   }
]
output [
   {
     name: "unique_ids:0"
     data_type: TYPE_INT64
     dims: [ 1 ]
     reshape: { shape: [ ] }
   }
]
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "precision_value" }}]
}}
instance_group {
  count: 1 #NUM_ENGINES
  gpus: [ 0 ]
  kind: KIND_GPU
}
dynamic_batching {
  preferred_batch_size: [ 1,2,4,8,16 ]
  max_queue_delay_microseconds: 30000
}
#db#dynamic_batching {
#db#    preferred_batch_size: 64#MAX_BATCH
#db#    max_queue_delay_microseconds: #MAX_QUEUE
#db#}
