name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - mlflow
      - mltable>=1.2.0
      - azureml-dataset-runtime[pandas,fuse]
      - azureml-telemetry
      - pandas
      - pillow
      - azureml-core
      - scikit-learn
      - cloudpickle
      - tensorflow==2.4.0
      - protobuf==3.20.0
