FROM docker.io/python
RUN pip install pip==20.0.2 --upgrade \ 
  numpy \
  pandas \
  scipy \
  scikit-learn \
  matplotlib \
  xgboost \
  lightgbm \
  dask \
  distributed \
  dask-ml \
  adlfs \
  fastparquet \
  pyarrow \
  mlflow \
  azureml-mlflow \
  azureml-dataprep \
  papermill 
    