name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - mlflow
      - mltable>=1.2.0
      - azureml-dataset-runtime[pandas,fuse]
      - azureml-telemetry
      - pandas
      - pillow
      - azureml-core
      - scikit-learn==0.24.2
      - cloudpickle==1.6.0
