name: credit-defaults-inference
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.17.0
      - cloudpickle==2.2.1
      - pandas==1.5.3
      - numpy==1.26.4
      - scikit-learn==1.5.2
      - scipy<1.14
      - psutil==5.8.0
      - azureml-inference-server-http
