channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=26.1.2
- pip:
  - mlflow==2.17.0
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.5.2
  - scipy==1.17.1
name: mlflow-env
