channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pip:
  - mlflow
  - cloudpickle==2.2.0
  - psutil==5.9.0
  - scikit-learn==1.5.1
  - inference-schema[numpy-support]==1.3.0
name: mlflow-env
