channels:
- conda-forge
dependencies:
- python=3.12
- pip
- pip:
  - mlflow
  - cloudpickle==3.1.2
  - psutil==5.9.4
  - scikit-learn==1.9.0
  - azureml-ai-monitoring
  - azureml-inference-server-http
name: mlflow-env
