name: 'Upload Artifact'
description: 'Uploads a specified folder as an artifact'
inputs:
  name:
    description: 'The name of the artifact'
    required: true
  path:
    description: 'The path to the artifact'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}