name: imagecnn_train_conda_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mldesigner==0.1.0b4
      - watchdog==0.10.3
      - tensorboard
      - pillow
      - numpy
      - pandas
      - protobuf==3.20.1
      - packaging==22.0
      - azureml-mlflow
