name: imagecnn_train_conda_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip>=22.0
  - pip:
      - mldesigner==0.1.0b4
      - watchdog>=2.1.0
      - torch==2.4.0
      - torchvision==0.19.0
      - tensorboard>=2.14.0
      - pillow==10.4.0
      - numpy==1.26.4
      - --extra-index-url=https://developer.download.nvidia.com/compute/redist/
      - nvidia-dali-cuda110
      - azureml-mlflow>=1.41.0
      - protobuf>=3.20.1
      - pandas>=1.5.0
      - packaging==22.0 # fix for https://github.com/pypa/setuptools/issues/4483