name: Python Quality Checks

on:
  workflow_dispatch:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.9"
      - run: pip install -r dev-requirements.txt
      - name: Check formatting for Python Scripts and Jupyter Notebooks
        run: black --check .